[package]
name = "teangaire"
version = "0.1.0"
authors = ["DÃ³nal Murray <donal.murray@cern.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
